[package]
name = "code-pick-recent-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
clap = "4.5.38"
serde = { version = "1.0.219", features = ["derive"] }
sonic-rs = "0.5.1"
dirs = "6.0.0"
text_io = "0.1.13"
