[package]
name = "codep"
version = "0.6.2"
edition = "2024"

[dependencies]
sonic-rs = "0.5.1"
dirs = "6.0.0"
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
urlencoding = "2.1.3"
anyhow = "1.0.98"
