[package]
name = "code-pick-recent-rs"
version = "0.3.1"
edition = "2024"

[dependencies]
sonic-rs = "0.5.1"
dirs = "6.0.0"
clap = { version = "4.5.38", features = ["derive"] }
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
